version: '3.5'

services:
  aplikasi:
    container_name: servis_django
    image: localhost/b3python
  databes:
    container_name: servis_db_postgres
    image: postgres:16.4-alpine
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  proksi:
    container_name: servis_reverse_proxy
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/nginx.conf