version: '3.5'

services:
  aplikasi:
    container_name: servis_django
    image: localhost/b3python
    ports:
      - "8000:8000"
  databes:
    container_name: servis_db_postgres
    image: postgres:16.4-alpine
    environment:
      POSTGRES_PASSWORD: example
  proksi:
    container_name: servis_reverse_proxy
    image: nginx:1.27.1-alpine-slim
    ports:
      - "80:80"
